# Generated by Django 3.1 on 2020-09-19 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamHead',
        ),
    ]
