# Generated by Django 3.1 on 2020-09-21 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team_head', '0002_employee_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_details',
            name='user',
        ),
    ]
